[workspace]
channels = ["rapidsai","conda-forge","bioconda","nvidia"]
name = "autoencoder_project"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10,<3.12"
numpy = "*"
pandas = "*"
matplotlib = "*"
pytorch = ">=2.7.1,<3"
#pytorch-cuda = "=13.0"
torchvision = ">=0.23.0,<0.24"
scikit-learn = "*"
jupyter = ">=1.1.1,<2"
quarto = "*"
opencv = "*"
pyproj= "*"
scipy = "*"
pyyaml = ">=6.0.2,<7"
snakemake = ">=9.9.0,<10"
scikit-image = ">=0.25.2,<0.26"
geopandas = ">=1.1.1,<2"
shapely = ">=2.1.1,<3"
timm = "==0.3.2"
transformers = ">=4.56.1,<5"
graphviz = ">=13.1.2,<14"
cupy = ">=13.6.0,<14"
cuml = ">=24.12.0,<25"
pip = ">=25.2,<26"
setuptools = ">=80.9.0,<81"
wheel = ">=0.45.1,<0.46"
hdbscan = ">=0.8.41,<0.9"
umap-learn = ">=0.5.9.post2,<0.6"
seaborn = ">=0.13.2,<0.14"
gdal = ">=3.10.3,<4"
rasterio = ">=1.4.4,<2"
sqlite = ">=3.51.2,<4"

[pypi-dependencies]
snakemake = "*"
torchsummary = "*"

[system-requirements]
cuda = "13" 


